server:
    port: 1210

spring:
    application:
        name: springboot_admin
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            url: jdbc:mysql://122.51.145.185:3437/springboot_admin?useUnicode=true&characterEncoding=utf-8&useSSL=false
            username: root
            password: 951210
            driver-class-name: com.mysql.jdbc.Driver
            # 连接池配置 #
            initial-size: 5 # 连接池初始化连接数
            max-active: 20  # 最大活跃连接数
            min-idle: 5     # 最小活跃连接数
            max-wait: 60000 # 获取连接等待超时时间
            max-pool-prepared-statement-per-connection-size: 20
            validation-query: SELECT 1 FROM DUAL
            filter: stat, wall # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，wall用于防火墙


# logging配置
logging:
    file: ${logging.path}/${spring.application.name}.log
    path: logs
    level:
        com.flouis: debug

# mybatis xml文件路径配置
mybatis:
    mapper-locations: classpath:mapper/*.xml

# swagger2开关
swagger2:
    enable: true
